AdminFormat.exe -tpl=../views/template.html -fmt=../views/gameparam/gamenotice.html
AdminFormat.exe -tpl=../views/template.html -fmt=../views/gameparam/hallmanager.html
AdminFormat.exe -tpl=../views/template.html -fmt=../views/gameparam/issueorders.html
AdminFormat.exe -tpl=../views/template.html -fmt=../views/gameparam/militaryexploitsquery.html
AdminFormat.exe -tpl=../views/template.html -fmt=../views/gameparam/syclemessage.html
AdminFormat.exe -tpl=../views/template.html -fmt=../views/incomeanalysis/chargerecord.html
AdminFormat.exe -tpl=../views/template.html -fmt=../views/incomeanalysis/gamecardgive.html
AdminFormat.exe -tpl=../views/template.html -fmt=../views/incomeanalysis/gamecarditem.html
AdminFormat.exe -tpl=../views/template.html -fmt=../views/incomeanalysis/gamecarduse.html
AdminFormat.exe -tpl=../views/template.html -fmt=../views/incomeanalysis/gamechargeitem.html
AdminFormat.exe -tpl=../views/template.html -fmt=../views/incomeanalysis/gamegolditem.html
AdminFormat.exe -tpl=../views/template.html -fmt=../views/incomeanalysis/gamewinstatic.html
AdminFormat.exe -tpl=../views/template.html -fmt=../views/incomeanalysis/issuerecord.html
AdminFormat.exe -tpl=../views/template.html -fmt=../views/qbackanalysis.html
AdminFormat.exe -tpl=../views/template.html -fmt=../views/registerGameApp.html
AdminFormat.exe -tpl=../views/template.html -fmt=../views/systemmanager/gamesetting.html
AdminFormat.exe -tpl=../views/template.html -fmt=../views/systemmanager/systemsetting.html
AdminFormat.exe -tpl=../views/template.html -fmt=../views/systemmanager/usermanager.html
AdminFormat.exe -tpl=../views/template.html -fmt=../views/vipmanager/labourunion.html
AdminFormat.exe -tpl=../views/template.html -fmt=../views/vipmanager/playermanager.html
AdminFormat.exe -tpl=../views/template.html -fmt=../views/vipmanager/proxymanager.html
AdminFormat.exe -tpl=../views/template.html -fmt=../views/vipmanager/unionermanager.html
AdminFormat.exe -tpl=../views/template.html -fmt=../views/waringlog.html
